<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BORSE-PC" ignored="66" name="Default test" tests="195" failures="26" timestamp="2020-02-06T04:06:48 IST" time="31136.076" errors="0">
  <testcase name="AddAlreadyUsedNVRManuallyTest" time="16.762" classname="testcases.NVRsTest"/>
  <testcase name="AddGroupAndCheckInMonitoringTest" time="67.857" classname="testcases.GroupsHierarchyTest"/>
  <testcase name="AddNVRAndCheckStatusVTest" time="87.054" classname="testcases.NVRsTest">
    <failure type="java.lang.AssertionError" message="expected [V] but found [NVR cannot be synced. Its system unique id belongs to another NVR.]">
      <![CDATA[java.lang.AssertionError: expected [V] but found [NVR cannot be synced. Its system unique id belongs to another NVR.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testcases.NVRsTest.AddNVRAndCheckStatusVTest(NVRsTest.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AddNVRAndCheckStatusVTest -->
  <testcase name="AddNVRAndPressApplyTest" time="44.165" classname="testcases.NVRsTest"/>
  <testcase name="AddNVRManuallyAndPressApplyTest" time="43.009" classname="testcases.NVRsTest"/>
  <testcase name="AddNVRManuallyAndPressCloseTest" time="22.672" classname="testcases.NVRsTest"/>
  <testcase name="AddNVRManuallyAndSwitchONSecuredTest" time="56.445" classname="testcases.NVRsTest"/>
  <testcase name="AddNVRManuallyCheckStatusTest" time="78.675" classname="testcases.NVRsTest">
    <failure type="java.lang.AssertionError" message="expected [V] but found [NVR cannot be synced. Its system unique id belongs to another NVR.]">
      <![CDATA[java.lang.AssertionError: expected [V] but found [NVR cannot be synced. Its system unique id belongs to another NVR.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testcases.NVRsTest.AddNVRManuallyCheckStatusTest(NVRsTest.java:507)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AddNVRManuallyCheckStatusTest -->
  <testcase name="AddNVRManuallyWithSecuredPortAndSwitchONSecuredTest" time="78.442" classname="testcases.NVRsTest">
    <failure type="java.lang.AssertionError" message="expected [V] but found [NVR cannot be synced. Its system unique id belongs to another NVR.]">
      <![CDATA[java.lang.AssertionError: expected [V] but found [NVR cannot be synced. Its system unique id belongs to another NVR.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testcases.NVRsTest.AddNVRManuallyWithSecuredPortAndSwitchONSecuredTest(NVRsTest.java:884)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AddNVRManuallyWithSecuredPortAndSwitchONSecuredTest -->
  <testcase name="AddNVRManuallyWithSecuredPortTest" time="210.829" classname="testcases.NVRsTest">
    <failure type="java.lang.AssertionError" message="expected [Communication Failure] but found [Connecting...]">
      <![CDATA[java.lang.AssertionError: expected [Communication Failure] but found [Connecting...]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testcases.NVRsTest.AddNVRManuallyWithSecuredPortTest(NVRsTest.java:812)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AddNVRManuallyWithSecuredPortTest -->
  <testcase name="AddNVRWithSecuredPortTest" time="122.984" classname="testcases.NVRsTest">
    <failure type="java.lang.AssertionError" message="expected [V] but found [NVR cannot be synced. Its system unique id belongs to another NVR.]">
      <![CDATA[java.lang.AssertionError: expected [V] but found [NVR cannot be synced. Its system unique id belongs to another NVR.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testcases.NVRsTest.AddNVRWithSecuredPortTest(NVRsTest.java:163)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AddNVRWithSecuredPortTest -->
  <testcase name="AddNewTourAndCancelTest" time="9.84" classname="testcases.ToursElementsTest"/>
  <testcase name="AddNewTourExitAndCancelTest" time="23.974" classname="testcases.ToursElementsTest"/>
  <testcase name="AddNewTourExitAndDoNotSaveTest" time="36.084" classname="testcases.ToursElementsTest"/>
  <testcase name="AddNewTourExitAndSaveTest" time="34.243" classname="testcases.ToursElementsTest"/>
  <testcase name="AddNewTourTest" time="12.069" classname="testcases.ToursTest"/>
  <testcase name="AddNewTourWithAllParametersTest" time="75.212" classname="testcases.ToursTest"/>
  <testcase name="AddNewTourWithoutViewAndCancelTest" time="5.052" classname="testcases.ToursElementsTest"/>
  <testcase name="AddNewTourWithoutViewExitAndCancelTest" time="19.415" classname="testcases.ToursElementsTest"/>
  <testcase name="AddNewTourWithoutViewExitAndDoNotSaveTest" time="26.237" classname="testcases.ToursElementsTest"/>
  <testcase name="AddNewTourWithoutViewExitAndSaveTest" time="4.519" classname="testcases.ToursElementsTest"/>
  <testcase name="AddNewViewAndPressCancelTest" time="9.578" classname="testcases.ViewsElementsTest"/>
  <testcase name="AddNewViewExitAndPressCancelTest" time="22.139" classname="testcases.ViewsElementsTest"/>
  <testcase name="AddNewViewExitAndPressDoNotSaveTest" time="29.021" classname="testcases.ViewsElementsTest"/>
  <testcase name="AddNewViewExitAndPressSaveTest" time="27.826" classname="testcases.ViewsElementsTest"/>
  <testcase name="AddNewViewWithLayoutExitAndCancelTest" time="18.742" classname="testcases.ViewsElementsTest"/>
  <testcase name="AddNewViewWithLayoutExitAndDoNotSaveTest" time="25.325" classname="testcases.ViewsElementsTest"/>
  <testcase name="AddNewViewWithLayoutExitAndSaveTest" time="5.686" classname="testcases.ViewsElementsTest"/>
  <testcase name="AddNewViewWithoutLayoutAndExitAndCancelTest" time="19.06" classname="testcases.ViewsElementsTest"/>
  <testcase name="AddNewViewWithoutLayoutAndExitAndDoNotSaveTest" time="24.816" classname="testcases.ViewsElementsTest"/>
  <testcase name="AddNewViewWithoutLayoutAndExitAndSaveTest" time="20.051" classname="testcases.ViewsElementsTest"/>
  <testcase name="AddNewWebPageExitAndSaveTest" time="0.911" classname="testcases.WebPagesElementsTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testcases.WebPagesElementsTest.AddNewWebPageExitAndSaveTest(WebPagesElementsTest.java:171)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AddNewWebPageExitAndSaveTest -->
  <testcase name="AddNewWebPageTest" time="0.588" classname="testcases.WebPagesTest"/>
  <testcase name="AddSubGroupTest" time="38.549" classname="testcases.GroupsHierarchyTest"/>
  <testcase name="AddViewAndCancelTest" time="10.971" classname="testcases.ToursElementsTest"/>
  <testcase name="AddViewExitAndCancelTest" time="27.086" classname="testcases.ToursElementsTest"/>
  <testcase name="AddViewExitAndDoNotSaveTest" time="40.22" classname="testcases.ToursElementsTest"/>
  <testcase name="AddViewExitAndSaveTest" time="40.224" classname="testcases.ToursElementsTest"/>
  <testcase name="AddViewTest" time="44.389" classname="testcases.ToursTest"/>
  <testcase name="CancelRemovalNVRsByButtonTest" time="16.505" classname="testcases.NVRsTest"/>
  <testcase name="CancelRemovalNVRsByIconTest" time="14.624" classname="testcases.NVRsTest"/>
  <testcase name="CancelWebPageRemovingByButtonTest" time="30.148" classname="testcases.WebPagesTest"/>
  <testcase name="CancelWebPageRemovingByIconTest" time="27.139" classname="testcases.WebPagesTest"/>
  <testcase name="ChangeIPAdressAndCheckStatusTest" time="191.566" classname="testcases.NVRsTest">
    <failure type="java.lang.AssertionError" message="expected [172.20.1.46IP] but found [IP]">
      <![CDATA[java.lang.AssertionError: expected [172.20.1.46IP] but found [IP]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testcases.NVRsTest.ChangeIPAdressAndCheckStatusTest(NVRsTest.java:1356)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ChangeIPAdressAndCheckStatusTest -->
  <testcase name="ChangeIPAdressExitCancelUnsavedChangesTest" time="209.854" classname="testcases.NVRsElementsTest">
    <failure type="java.lang.AssertionError" message="expected [172.20.1.46IP30] but found [IP30]">
      <![CDATA[java.lang.AssertionError: expected [172.20.1.46IP30] but found [IP30]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testcases.NVRsElementsTest.ChangeIPAdressExitCancelUnsavedChangesTest(NVRsElementsTest.java:377)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ChangeIPAdressExitCancelUnsavedChangesTest -->
  <testcase name="ChangeIPAdressExitPressDontSaveUnsavedChangesTest" time="255.122" classname="testcases.NVRsElementsTest"/>
  <testcase name="ChangeIPAdressExitPressSaveUnsavedChangesTest" time="244.623" classname="testcases.NVRsElementsTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testcases.NVRsElementsTest.ChangeIPAdressExitPressSaveUnsavedChangesTest(NVRsElementsTest.java:472)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ChangeIPAdressExitPressSaveUnsavedChangesTest -->
  <testcase name="ChangeIPAdressPressCancelExitTest" time="234.968" classname="testcases.NVRsElementsTest"/>
  <testcase name="ChangeLayoutAndPressCancelTest" time="21.891" classname="testcases.ViewsElementsTest">
    <failure type="java.lang.AssertionError" message="expected [5] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at testcases.ViewsElementsTest.ChangeLayoutAndPressCancelTest(ViewsElementsTest.java:1331)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ChangeLayoutAndPressCancelTest -->
  <testcase name="ChangeLayoutExitAndPressCancelTest" time="31.849" classname="testcases.ViewsElementsTest"/>
  <testcase name="ChangeLayoutExitAndPressDontSaveTest" time="47.629" classname="testcases.ViewsElementsTest"/>
  <testcase name="ChangeLayoutExitAndPressSaveTest" time="52.781" classname="testcases.ViewsElementsTest">
    <failure type="java.lang.AssertionError" message="expected [9] but found [16]">
      <![CDATA[java.lang.AssertionError: expected [9] but found [16]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at testcases.ViewsElementsTest.ChangeLayoutExitAndPressSaveTest(ViewsElementsTest.java:1560)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ChangeLayoutExitAndPressSaveTest -->
  <testcase name="ChangeNameAndCancelTest" time="8.828" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeNameAndPressCancelTest" time="14.445" classname="testcases.ViewsElementsTest"/>
  <testcase name="ChangeNameExitAndCancelTest" time="22.977" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeNameExitAndDoNotSaveTest" time="48.088" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeNameExitAndPressCancelTest" time="25.457" classname="testcases.ViewsElementsTest"/>
  <testcase name="ChangeNameExitAndPressDoNotSaveTest" time="76.945" classname="testcases.ViewsElementsTest"/>
  <testcase name="ChangeNameExitAndPressSaveTest" time="57.331" classname="testcases.ViewsElementsTest"/>
  <testcase name="ChangeNameExitAndSaveTest" time="42.028" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeNameExitPressDontSaveUnsavedChangesTest" time="74.714" classname="testcases.NVRsElementsTest"/>
  <testcase name="ChangeNameExitPressSaveUnsavedChangesTest" time="262.197" classname="testcases.NVRsElementsTest"/>
  <testcase name="ChangeNamePressCancelTest" time="11.109" classname="testcases.NVRsElementsTest"/>
  <testcase name="ChangeNameTest" time="31.097" classname="testcases.NVRsTest"/>
  <testcase name="ChangeNameTest" time="43.573" classname="testcases.ToursTest"/>
  <testcase name="ChangeNameTest" time="34.135" classname="testcases.WebPagesTest"/>
  <testcase name="ChangeOrderForViewTest" time="7.0" classname="testcases.ToursTest"/>
  <testcase name="ChangePasswordToInvalidAndCheckStatusTest" time="214.952" classname="testcases.NVRsTest"/>
  <testcase name="ChangePortAndCheckStatusTest" time="140.484" classname="testcases.NVRsTest">
    <failure type="java.lang.AssertionError" message="expected [85] but found [8]">
      <![CDATA[java.lang.AssertionError: expected [85] but found [8]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testcases.NVRsTest.ChangePortAndCheckStatusTest(NVRsTest.java:1407)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ChangePortAndCheckStatusTest -->
  <testcase name="ChangePortExitCancelUnsavedChangesTest" time="31.277" classname="testcases.NVRsElementsTest"/>
  <testcase name="ChangePortExitPressDontSaveUnsavedChangesTest" time="246.741" classname="testcases.NVRsElementsTest"/>
  <testcase name="ChangePortExitPressSaveUnsavedChangesTest" time="243.217" classname="testcases.NVRsElementsTest"/>
  <testcase name="ChangePortPressCancelTest" time="27.192" classname="testcases.NVRsElementsTest">
    <failure type="java.lang.AssertionError" message="expected [80] but found [291]">
      <![CDATA[java.lang.AssertionError: expected [80] but found [291]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testcases.NVRsElementsTest.ChangePortPressCancelTest(NVRsElementsTest.java:557)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ChangePortPressCancelTest -->
  <testcase name="ChangeRefreshTimeStatusTest" time="26.078" classname="testcases.WebPagesTest"/>
  <testcase name="ChangeRefreshTimeValueBySpinnerTest" time="100.229" classname="testcases.WebPagesTest"/>
  <testcase name="ChangeRefreshTimeValueTest" time="28.479" classname="testcases.WebPagesTest"/>
  <testcase name="ChangeRemarksAndCancelTest" time="5.673" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeRemarksAndPressCancelTest" time="79.273" classname="testcases.ViewsElementsTest"/>
  <testcase name="ChangeRemarksExitAndCancelTest" time="26.03" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeRemarksExitAndDoNotSaveTest" time="43.166" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeRemarksExitAndPressCancelTest" time="40.223" classname="testcases.ViewsElementsTest"/>
  <testcase name="ChangeRemarksExitAndPressDoNotSaveTest" time="49.871" classname="testcases.ViewsElementsTest"/>
  <testcase name="ChangeRemarksExitAndPressSaveTest" time="37.962" classname="testcases.ViewsElementsTest"/>
  <testcase name="ChangeRemarksExitAndSaveTest" time="45.002" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeRemarksTest" time="36.334" classname="testcases.ToursTest"/>
  <testcase name="ChangeRemarksTest" time="29.097" classname="testcases.WebPagesTest"/>
  <testcase name="ChangeSecuredAndCheckStatusTest" time="265.152" classname="testcases.NVRsTest">
    <failure type="java.lang.AssertionError" message="expected [V] but found [NVR cannot be synced. Its system unique id belongs to another NVR.]">
      <![CDATA[java.lang.AssertionError: expected [V] but found [NVR cannot be synced. Its system unique id belongs to another NVR.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testcases.NVRsTest.ChangeSecuredAndCheckStatusTest(NVRsTest.java:1533)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ChangeSecuredAndCheckStatusTest -->
  <testcase name="ChangeURLTest" time="32.137" classname="testcases.WebPagesTest"/>
  <testcase name="ChangeUserNameAndPressCancel" time="189.549" classname="testcases.NVRsElementsTest"/>
  <testcase name="ChangeUserNameExitCancelUnsavedChangesTest" time="227.12" classname="testcases.NVRsElementsTest"/>
  <testcase name="ChangeUserNameExitPressDontSaveUnsavedChangesTest" time="235.467" classname="testcases.NVRsElementsTest"/>
  <testcase name="ChangeUserNameExitPressSaveUnsavedChangesTest" time="235.408" classname="testcases.NVRsElementsTest"/>
  <testcase name="ChangeUserNameToInvalidAndCheckStatusTest" time="211.337" classname="testcases.NVRsTest"/>
  <testcase name="ChangeViewTimeAndCancelTest" time="5.381" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeViewTimeBySpinnersAndCancelTest" time="8.436" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeViewTimeBySpinnersExitAndCancelTest" time="46.583" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeViewTimeBySpinnersExitAndDoNotSaveTest" time="72.792" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeViewTimeBySpinnersExitAndSaveTest" time="51.012" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeViewTimeBySpinnersTest" time="50.916" classname="testcases.ToursTest"/>
  <testcase name="ChangeViewTimeExitAndCancelTest" time="22.479" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeViewTimeExitAndDoNotSaveTest" time="43.035" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeViewTimeExitAndSaveTest" time="43.023" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeViewTimeTest" time="10.756" classname="testcases.ToursTest">
    <failure type="java.lang.AssertionError" message="expected [72728] but found [7272]">
      <![CDATA[java.lang.AssertionError: expected [72728] but found [7272]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testcases.ToursTest.ChangeViewTimeTest(ToursTest.java:750)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ChangeViewTimeTest -->
  <testcase name="ChangeViewTimeToLessThanMinValueTest" time="8.2" classname="testcases.ToursTest"/>
  <testcase name="ChangeViewTimeToMoreThanMaxValueTest" time="7.601" classname="testcases.ToursTest"/>
  <testcase name="ChangeVisibilityStatusAndCancelTest" time="7.383" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeVisibilityStatusAndPressCancelTest" time="14.66" classname="testcases.ViewsElementsTest"/>
  <testcase name="ChangeVisibilityStatusExitAndCancelTest" time="19.74" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeVisibilityStatusExitAndDoNotSaveTest" time="37.735" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeVisibilityStatusExitAndPressCancelTest" time="66.895" classname="testcases.ViewsElementsTest"/>
  <testcase name="ChangeVisibilityStatusExitAndPressDoNotSaveTest" time="43.029" classname="testcases.ViewsElementsTest"/>
  <testcase name="ChangeVisibilityStatusExitAndPressSaveTest" time="26.26" classname="testcases.ViewsElementsTest"/>
  <testcase name="ChangeVisibilityStatusExitAndSaveTest" time="42.02" classname="testcases.ToursElementsTest"/>
  <testcase name="ChangeVisibilityStatusTest" time="42.833" classname="testcases.ToursTest"/>
  <testcase name="ChangeVisibilityStatusTest" time="34.776" classname="testcases.WebPagesTest"/>
  <testcase name="CheckPropertiesAfterChangeIPAdressTest" time="59.101" classname="testcases.NVRsElementsTest">
    <failure type="java.lang.AssertionError" message="expected [] but found [172.20.1.42 Name]">
      <![CDATA[java.lang.AssertionError: expected [] but found [172.20.1.42 Name]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testcases.NVRsElementsTest.CheckPropertiesAfterChangeIPAdressTest(NVRsElementsTest.java:522)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CheckPropertiesAfterChangeIPAdressTest -->
  <testcase name="CheckPropertiesAfterChangeNameTest" time="62.648" classname="testcases.NVRsElementsTest"/>
  <testcase name="CheckPropertiesAfterChangePasswordTest" time="67.348" classname="testcases.NVRsElementsTest"/>
  <testcase name="CheckPropertiesAfterChangePortTest" time="74.903" classname="testcases.NVRsElementsTest"/>
  <testcase name="CheckPropertiesAfterChangeUserNameTest" time="65.015" classname="testcases.NVRsElementsTest">
    <failure type="java.lang.AssertionError" message="expected [172.20.1.46] but found [172.20.1.42 Name]">
      <![CDATA[java.lang.AssertionError: expected [172.20.1.46] but found [172.20.1.42 Name]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testcases.NVRsElementsTest.CheckPropertiesAfterChangeUserNameTest(NVRsElementsTest.java:1126)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CheckPropertiesAfterChangeUserNameTest -->
  <testcase name="ClearViewAndPressCancelTest" time="23.975" classname="testcases.ViewsElementsTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at testcases.ViewsElementsTest.ClearViewAndPressCancelTest(ViewsElementsTest.java:1107)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ClearViewAndPressCancelTest -->
  <testcase name="ClearViewExitAndPressCancelTest" time="52.279" classname="testcases.ViewsElementsTest"/>
  <testcase name="ClearViewExitAndPressDoNotSaveTest" time="72.108" classname="testcases.ViewsElementsTest"/>
  <testcase name="ClearViewExitAndPressSaveTest" time="34.385" classname="testcases.ViewsElementsTest"/>
  <testcase name="DecreasePortExitCancelUnsavedChangesTest" time="15.426" classname="testcases.NVRsElementsTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at testcases.NVRsElementsTest.DecreasePortExitCancelUnsavedChangesTest(NVRsElementsTest.java:811)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- DecreasePortExitCancelUnsavedChangesTest -->
  <testcase name="DeleteAllViewsAndCancelTest" time="6.205" classname="testcases.ToursElementsTest"/>
  <testcase name="DeleteAllViewsExitAndCancelTest" time="25.024" classname="testcases.ToursElementsTest"/>
  <testcase name="DeleteAllViewsExitAndDoNotSaveTest" time="31.253" classname="testcases.ToursElementsTest"/>
  <testcase name="DeleteAllViewsExitAndSaveTest" time="4.525" classname="testcases.ToursElementsTest"/>
  <testcase name="DeleteAllViewsTest" time="5.96" classname="testcases.ToursTest"/>
  <testcase name="DeleteGroupAndCheckInMonitoringTest" time="76.085" classname="testcases.GroupsHierarchyTest"/>
  <testcase name="DeleteGroupAndPressNoTest" time="30.662" classname="testcases.GroupsHierarchyTest"/>
  <testcase name="DeleteOneNVRClickOnAnotherNVRAndCheckPropertiesPanelTest" time="28.332" classname="testcases.NVRsTest"/>
  <testcase name="DeleteResourceByButtonAndCancelRemovingTest" time="4.62" classname="testcases.GroupsHierarchyTest"/>
  <testcase name="DeleteResourceByButtonAndCheckInMonitoringTest" time="4.178" classname="testcases.GroupsHierarchyTest"/>
  <testcase name="DeleteTourByButtonAndPressNoTest" time="33.56" classname="testcases.ToursTest"/>
  <testcase name="DeleteTourByButtonTest" time="31.731" classname="testcases.ToursTest"/>
  <testcase name="DeleteTourByIconAndPressNoTest" time="18.309" classname="testcases.ToursTest"/>
  <testcase name="DeleteTourByIconTest" time="68.095" classname="testcases.ToursTest"/>
  <testcase name="DeleteURLTest" time="11.076" classname="testcases.WebPagesTest"/>
  <testcase name="DeleteViewAndCancelTest" time="3.385" classname="testcases.ToursElementsTest"/>
  <testcase name="DeleteViewExitAndCancelTest" time="0.343" classname="testcases.ToursElementsTest"/>
  <testcase name="DeleteViewExitAndDoNotSaveTest" time="23.223" classname="testcases.ToursElementsTest"/>
  <testcase name="DeleteViewExitAndSaveTest" time="6.438" classname="testcases.ToursElementsTest"/>
  <testcase name="DeleteViewFromViewsPageTest" time="59.838" classname="testcases.ToursTest"/>
  <testcase name="DeleteViewTest" time="5.145" classname="testcases.ToursTest"/>
  <testcase name="DeleteWebPageByButtonTest" time="73.321" classname="testcases.WebPagesTest"/>
  <testcase name="DeleteWebPageByIconTest" time="13.471" classname="testcases.WebPagesTest"/>
  <testcase name="DragResourceToGroupTest" time="46.598" classname="testcases.GroupsHierarchyTest"/>
  <testcase name="FilterDiscoveredNVRsTest" time="21.614" classname="testcases.NVRsTest">
    <failure type="java.lang.AssertionError" message="expected [172.20.1.53] but found [172.20.1.50]">
      <![CDATA[java.lang.AssertionError: expected [172.20.1.53] but found [172.20.1.50]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testcases.NVRsTest.FilterDiscoveredNVRsTest(NVRsTest.java:280)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- FilterDiscoveredNVRsTest -->
  <testcase name="FilterNVRsTest" time="5.493" classname="testcases.NVRsTest"/>
  <testcase name="FilterToursTest" time="3.179" classname="testcases.ToursTest"/>
  <testcase name="FilterViewsTest" time="5.55" classname="testcases.ToursTest"/>
  <testcase name="IncreasePortAndPressCancel" time="133.052" classname="testcases.NVRsElementsTest">
    <failure type="org.openqa.selenium.TimeoutException" message="Expected condition failed: waiting for value to contain &amp;quot;false&amp;quot;. Current value: &amp;quot;null&amp;quot; (tried for 15 second(s) with 500 MILLISECONDS interval)
Build info: version: &amp;apos;3.9.1&amp;apos;, revision: &amp;apos;63f7b50&amp;apos;, time: &amp;apos;2018-02-07T22:25:02.294Z&amp;apos;
System info: host: &amp;apos;BORSE-PC&amp;apos;, ip: &amp;apos;172.20.1.42&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_202&amp;apos;
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {browserName: internet explorer, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enableElementCacheCleanup: true, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.enableFullPageScreenshot: true, ie.ensureCleanSession: true, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ie.forceShellWindowsApi: false, ie.useLegacyFileUploadDialogHandling: false, ignoreProtectedModeSettings: true, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:2240/, nativeEvents: true, requireWindowFocus: false}, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss, version: 11}
Session ID: 833dfb4c-cb45-4441-a61c-bc2852701c32">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for value to contain "false". Current value: "null" (tried for 15 second(s) with 500 MILLISECONDS interval)
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'BORSE-PC', ip: '172.20.1.42', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_202'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {browserName: internet explorer, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enableElementCacheCleanup: true, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.enableFullPageScreenshot: true, ie.ensureCleanSession: true, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ie.forceShellWindowsApi: false, ie.useLegacyFileUploadDialogHandling: false, ignoreProtectedModeSettings: true, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:2240/, nativeEvents: true, requireWindowFocus: false}, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss, version: 11}
Session ID: 833dfb4c-cb45-4441-a61c-bc2852701c32
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:82)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
at pageObjects.NVRsPage.CancelChangesButton(NVRsPage.java:432)
at testcases.NVRsElementsTest.IncreasePortAndPressCancel(NVRsElementsTest.java:776)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- IncreasePortAndPressCancel -->
  <testcase name="IncreasePortExitPressDontSaveUnsavedChangesTest" time="190.897" classname="testcases.NVRsElementsTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at testcases.NVRsElementsTest.IncreasePortExitPressDontSaveUnsavedChangesTest(NVRsElementsTest.java:851)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- IncreasePortExitPressDontSaveUnsavedChangesTest -->
  <testcase name="InputInvalidIPAdressInAddNVRManualyTest" time="22.703" classname="testcases.NVRsTest"/>
  <testcase name="InputInvalidPasswordInAddNVRManualyTest" time="46.346" classname="testcases.NVRsTest"/>
  <testcase name="InputInvalidPortInAddNVRManualyTest" time="50.548" classname="testcases.NVRsTest"/>
  <testcase name="InputInvalidUserNameInAddNVRManualyTest" time="47.361" classname="testcases.NVRsTest"/>
  <testcase name="MultipleNVRsAdditingTest" time="78.435" classname="testcases.NVRsTest">
    <failure type="java.lang.AssertionError" message="expected [12] but found [11]">
      <![CDATA[java.lang.AssertionError: expected [12] but found [11]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at testcases.NVRsTest.MultipleNVRsAdditingTest(NVRsTest.java:354)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MultipleNVRsAdditingTest -->
  <testcase name="NewTourWithEmptyViewTest" time="18.082" classname="testcases.ToursTest"/>
  <testcase name="RemoveNVRsByIconTest" time="24.341" classname="testcases.NVRsTest"/>
  <testcase name="RenameGroupAndCheckInMonitoringTest" time="46.036" classname="testcases.GroupsHierarchyTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at testcases.GroupsHierarchyTest.RenameGroupAndCheckInMonitoringTest(GroupsHierarchyTest.java:309)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- RenameGroupAndCheckInMonitoringTest -->
  <testcase name="RenameGroupAndClickCancelIconTest" time="2.687" classname="testcases.GroupsHierarchyTest"/>
  <testcase name="ResourcesFilterTest" time="3.731" classname="testcases.GroupsHierarchyTest"/>
  <testcase name="AddNewViewTest" time="56.742" classname="testcases.ViewsTest"/>
  <testcase name="AddNewViewWithoutLayoutTest" time="6.122" classname="testcases.ViewsTest"/>
  <testcase name="CancelDeletingViewByButton" time="31.075" classname="testcases.ViewsTest"/>
  <testcase name="CancelRemovingViewByIconTest" time="32.095" classname="testcases.ViewsTest"/>
  <testcase name="ChangeLayoutTest" time="94.151" classname="testcases.ViewsTest"/>
  <testcase name="ChangeNameTest" time="60.372" classname="testcases.ViewsTest">
    <failure type="org.openqa.selenium.NoSuchElementException" message="Unable to find element with xpath == //div[@class=&amp;apos;ui-grid-canvas&amp;apos;]//div[@title=&amp;apos;new view name12482&amp;apos;] (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: &amp;apos;3.9.1&amp;apos;, revision: &amp;apos;63f7b50&amp;apos;, time: &amp;apos;2018-02-07T22:25:02.294Z&amp;apos;
System info: host: &amp;apos;BORSE-PC&amp;apos;, ip: &amp;apos;172.20.1.42&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_202&amp;apos;
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {browserName: internet explorer, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enableElementCacheCleanup: true, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.enableFullPageScreenshot: true, ie.ensureCleanSession: true, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ie.forceShellWindowsApi: false, ie.useLegacyFileUploadDialogHandling: false, ignoreProtectedModeSettings: true, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:4384/, nativeEvents: true, requireWindowFocus: false}, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss, version: 11}
Session ID: d58660a3-2321-488c-a681-048067da625c
*** Element info: {Using=xpath, value=//div[@class=&amp;apos;ui-grid-canvas&amp;apos;]//div[@title=&amp;apos;new view name12482&amp;apos;]}">
      <![CDATA[org.openqa.selenium.NoSuchElementException: Unable to find element with xpath == //div[@class='ui-grid-canvas']//div[@title='new view name12482'] (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'BORSE-PC', ip: '172.20.1.42', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_202'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {browserName: internet explorer, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enableElementCacheCleanup: true, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.enableFullPageScreenshot: true, ie.ensureCleanSession: true, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ie.forceShellWindowsApi: false, ie.useLegacyFileUploadDialogHandling: false, ignoreProtectedModeSettings: true, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:4384/, nativeEvents: true, requireWindowFocus: false}, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss, version: 11}
Session ID: d58660a3-2321-488c-a681-048067da625c
*** Element info: {Using=xpath, value=//div[@class='ui-grid-canvas']//div[@title='new view name12482']}
at sun.reflect.GeneratedConstructorAccessor35.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:371)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:473)
at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
at pageObjects.ViewsPage.ClickOnViewByName(ViewsPage.java:378)
at testcases.ViewsTest.ChangeNameTest(ViewsTest.java:283)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ChangeNameTest -->
  <testcase name="ChangeRemarksTest" time="40.272" classname="testcases.ViewsTest"/>
  <testcase name="ChangeVisibilityStatusTest" time="57.713" classname="testcases.ViewsTest"/>
  <testcase name="ClearViewAndDragResourceTest" time="81.31" classname="testcases.ViewsTest"/>
  <testcase name="ClearViewTest" time="81.395" classname="testcases.ViewsTest"/>
  <testcase name="DeleteViewByButtonTest" time="43.759" classname="testcases.ViewsTest"/>
  <testcase name="DeleteViewByIconTest" time="43.282" classname="testcases.ViewsTest"/>
  <testcase name="ResourceFilterTest" time="7.263" classname="testcases.ViewsTest"/>
  <testcase name="SelectNVRandPressCancelTest" time="25.81" classname="testcases.NVRsTest"/>
  <testcase name="SortingDiscoveredNVRsTest" time="23.83" classname="testcases.NVRsTest"/>
  <testcase name="SortingNVRsByIPAdressTest" time="142.632" classname="testcases.NVRsTest"/>
  <testcase name="SortingNVRsByNameTest" time="12.387" classname="testcases.NVRsTest"/>
  <testcase name="SortingNVRsByVersionTest" time="11.307" classname="testcases.NVRsTest"/>
  <testcase name="SwitchOffStorageDefinitionsAndPressNoTest" time="48.779" classname="testcases.NVRsTest"/>
  <testcase name="SwitchStorageDefinitionsAndPressCancelTest" time="27.788" classname="testcases.NVRsElementsTest"/>
  <testcase name="SwitchStorageDefinitionsExitAndPressCancelTest" time="44.153" classname="testcases.NVRsElementsTest"/>
  <testcase name="SwitchStorageDefinitionsExitAndPressDontSaveButtonTest" time="72.719" classname="testcases.NVRsElementsTest"/>
  <testcase name="SwitchStorageDefinitionsExitAndPressSaveButtonTest" time="73.805" classname="testcases.NVRsElementsTest"/>
  <testcase name="SwitchStorageDefinitionsTest" time="35.777" classname="testcases.NVRsTest"/>
  <testcase name="ViewsFilterTest" time="2.686" classname="testcases.ViewsTest"/>
  <testcase name="WebPagesFilterTest" time="12.455" classname="testcases.WebPagesTest"/>
  <testcase name="addViewTest" time="24.608" classname="testcases.MonitoringView"/>
  <testcase name="uDecreasePortExitPressSaveUnsavedChangesTest" time="186.786" classname="testcases.NVRsElementsTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at testcases.NVRsElementsTest.uDecreasePortExitPressSaveUnsavedChangesTest(NVRsElementsTest.java:901)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- uDecreasePortExitPressSaveUnsavedChangesTest -->
  <testcase name="ChangeNameExitCancelUnsavedChangesExitCancelTest" time="29.019" classname="testcases.NVRsElementsTest"/>
  <testcase name="RemoveNVRsByButtonTest" time="28.831" classname="testcases.NVRsTest"/>
  <testcase name="CancelDeletingViewByButton" time="0.0" classname="testcases.MonitoringView">
    <ignored/>
  </testcase> <!-- CancelDeletingViewByButton -->
  <testcase name="ChangeNameExitAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeNameExitAndCancelTest -->
  <testcase name="ChangeVisibilityStatusExitAndDoNotSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeVisibilityStatusExitAndDoNotSaveTest -->
  <testcase name="ChangeNameAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeNameAndCancelTest -->
  <testcase name="ChangeRefreshTimeStatusExitAndSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRefreshTimeStatusExitAndSaveTest -->
  <testcase name="CancelRemovingViewByIconTest" time="0.0" classname="testcases.MonitoringView">
    <ignored/>
  </testcase> <!-- CancelRemovingViewByIconTest -->
  <testcase name="AddNewWebPageInputParametersTest" time="0.0" classname="testcases.WebPagesTest">
    <ignored/>
  </testcase> <!-- AddNewWebPageInputParametersTest -->
  <testcase name="DeleteURLExitAndSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- DeleteURLExitAndSaveTest -->
  <testcase name="ChangeRemarksAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRemarksAndCancelTest -->
  <testcase name="ClearViewAndDragResourceTest" time="0.0" classname="testcases.MonitoringView">
    <ignored/>
  </testcase> <!-- ClearViewAndDragResourceTest -->
  <testcase name="DragResourceTest" time="0.0" classname="testcases.MonitoringView">
    <ignored/>
  </testcase> <!-- DragResourceTest -->
  <testcase name="AddNewViewWithoutLayoutTest" time="0.0" classname="testcases.MonitoringView">
    <ignored/>
  </testcase> <!-- AddNewViewWithoutLayoutTest -->
  <testcase name="ChangeVisibilityStatusExitAndSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeVisibilityStatusExitAndSaveTest -->
  <testcase name="ChangeUserNameToValidAndCheckStatusTest" time="0.0" classname="testcases.NVRsTest">
    <ignored/>
  </testcase> <!-- ChangeUserNameToValidAndCheckStatusTest -->
  <testcase name="ChangeRefreshTimeValueExitAndDoNotSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRefreshTimeValueExitAndDoNotSaveTest -->
  <testcase name="ResourceFilterTest" time="0.0" classname="testcases.MonitoringView">
    <ignored/>
  </testcase> <!-- ResourceFilterTest -->
  <testcase name="ChangeURLExitAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeURLExitAndCancelTest -->
  <testcase name="ChangeRefreshTimeStatusAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRefreshTimeStatusAndCancelTest -->
  <testcase name="DeleteViewByButtonTest" time="0.0" classname="testcases.MonitoringView">
    <ignored/>
  </testcase> <!-- DeleteViewByButtonTest -->
  <testcase name="AddNewWebPageExitAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- AddNewWebPageExitAndCancelTest -->
  <testcase name="ChangeRemarksExitAndSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRemarksExitAndSaveTest -->
  <testcase name="ChangeRefreshTimeValueBySpinnerAndSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRefreshTimeValueBySpinnerAndSaveTest -->
  <testcase name="ChangeRefreshTimeValueExitAndSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRefreshTimeValueExitAndSaveTest -->
  <testcase name="ChangeRefreshTimeValueExitAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRefreshTimeValueExitAndCancelTest -->
  <testcase name="AddNewWebPageAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- AddNewWebPageAndCancelTest -->
  <testcase name="AddNewWebPageInputURLExitAndSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- AddNewWebPageInputURLExitAndSaveTest -->
  <testcase name="ChangeVisibilityStatusExitAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeVisibilityStatusExitAndCancelTest -->
  <testcase name="DeleteOneNVRAndCheckPropertiesPanelTest" time="0.0" classname="testcases.NVRsTest">
    <ignored/>
  </testcase> <!-- DeleteOneNVRAndCheckPropertiesPanelTest -->
  <testcase name="DeleteURLExitAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- DeleteURLExitAndCancelTest -->
  <testcase name="ChangeStorageDefinitionsTest" time="0.0" classname="testcases.NVRsTest">
    <ignored/>
  </testcase> <!-- ChangeStorageDefinitionsTest -->
  <testcase name="ChangeURLExitAndSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeURLExitAndSaveTest -->
  <testcase name="ChangeRefreshTimeValueAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRefreshTimeValueAndCancelTest -->
  <testcase name="ChangeStorageDefinitionsAndPressCancelTest" time="0.0" classname="testcases.NVRsElementsTest">
    <ignored/>
  </testcase> <!-- ChangeStorageDefinitionsAndPressCancelTest -->
  <testcase name="IncreasePortInAddNVRManualyWindowTest" time="0.0" classname="testcases.NVRsTest">
    <ignored/>
  </testcase> <!-- IncreasePortInAddNVRManualyWindowTest -->
  <testcase name="DeleteViewByIconTest" time="0.0" classname="testcases.MonitoringView">
    <ignored/>
  </testcase> <!-- DeleteViewByIconTest -->
  <testcase name="DeleteCameraAndCheckInViewTest" time="0.0" classname="testcases.ViewsTest">
    <ignored/>
  </testcase> <!-- DeleteCameraAndCheckInViewTest -->
  <testcase name="AddNVRWithSecuredPortAndSwitchOffSecuredStatusTest" time="0.0" classname="testcases.NVRsTest">
    <ignored/>
  </testcase> <!-- AddNVRWithSecuredPortAndSwitchOffSecuredStatusTest -->
  <testcase name="ChangePortToSecuredAndCheckStatusTest" time="0.0" classname="testcases.NVRsTest">
    <ignored/>
  </testcase> <!-- ChangePortToSecuredAndCheckStatusTest -->
  <testcase name="ChangeNameExitAndSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeNameExitAndSaveTest -->
  <testcase name="DeleteCameraAndCheckInViewTest" time="0.0" classname="testcases.MonitoringView">
    <ignored/>
  </testcase> <!-- DeleteCameraAndCheckInViewTest -->
  <testcase name="changelayoutTest" time="0.0" classname="testcases.MonitoringView">
    <ignored/>
  </testcase> <!-- changelayoutTest -->
  <testcase name="ChangeRefreshTimeValueBySpinnerExitAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRefreshTimeValueBySpinnerExitAndCancelTest -->
  <testcase name="ChangeRemarksExitAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRemarksExitAndCancelTest -->
  <testcase name="DeleteURLAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- DeleteURLAndCancelTest -->
  <testcase name="AddNewWebPageInputURLExitAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- AddNewWebPageInputURLExitAndCancelTest -->
  <testcase name="DragGroupToGroupTest" time="0.0" classname="testcases.GroupsHierarchyTest">
    <ignored/>
  </testcase> <!-- DragGroupToGroupTest -->
  <testcase name="ViewsFilterTest" time="0.0" classname="testcases.MonitoringView">
    <ignored/>
  </testcase> <!-- ViewsFilterTest -->
  <testcase name="ChangeRefreshTimeValueBySpinnerAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRefreshTimeValueBySpinnerAndCancelTest -->
  <testcase name="ChangeURLExitAndDoNotSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeURLExitAndDoNotSaveTest -->
  <testcase name="DeleteURLExitAndDoNotSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- DeleteURLExitAndDoNotSaveTest -->
  <testcase name="ChangeStorageDefinitionsExitCancelUnsavedChangesTest" time="0.0" classname="testcases.NVRsElementsTest">
    <ignored/>
  </testcase> <!-- ChangeStorageDefinitionsExitCancelUnsavedChangesTest -->
  <testcase name="AddNewWebPageExitAndDoNotSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- AddNewWebPageExitAndDoNotSaveTest -->
  <testcase name="SwitchOffStorageDefinitionsTest" time="0.0" classname="testcases.NVRsTest">
    <ignored/>
  </testcase> <!-- SwitchOffStorageDefinitionsTest -->
  <testcase name="ChangeLayoutTest" time="0.0" classname="testcases.MonitoringView">
    <ignored/>
  </testcase> <!-- ChangeLayoutTest -->
  <testcase name="ChangePortBySpinnersTest" time="0.0" classname="testcases.NVRsTest">
    <ignored/>
  </testcase> <!-- ChangePortBySpinnersTest -->
  <testcase name="DecreasePortInAddNVRManualyWindowTest" time="0.0" classname="testcases.NVRsTest">
    <ignored/>
  </testcase> <!-- DecreasePortInAddNVRManualyWindowTest -->
  <testcase name="ChangeRefreshTimeStatusExitAndDoNoTSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRefreshTimeStatusExitAndDoNoTSaveTest -->
  <testcase name="ChangePortToValidAndCheckStatusTest" time="0.0" classname="testcases.NVRsTest">
    <ignored/>
  </testcase> <!-- ChangePortToValidAndCheckStatusTest -->
  <testcase name="ChangeRefreshTimeStatusExitAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRefreshTimeStatusExitAndCancelTest -->
  <testcase name="ChangeNameExitAndDoNotSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeNameExitAndDoNotSaveTest -->
  <testcase name="ChangeRefreshTimeValueBySpinnerExitAndDoNotSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRefreshTimeValueBySpinnerExitAndDoNotSaveTest -->
  <testcase name="ChangeVisibilityStatusAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeVisibilityStatusAndCancelTest -->
  <testcase name="AddNewWebPageInputURLAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- AddNewWebPageInputURLAndCancelTest -->
  <testcase name="ChangeRemarksExitAndDoNotSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeRemarksExitAndDoNotSaveTest -->
  <testcase name="ChangeURLAndCancelTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- ChangeURLAndCancelTest -->
  <testcase name="AddNewWebPageInputURLExitAndDoNotSaveTest" time="0.0" classname="testcases.WebPagesElementsTest">
    <ignored/>
  </testcase> <!-- AddNewWebPageInputURLExitAndDoNotSaveTest -->
</testsuite> <!-- Default test -->
